# Generated by Django 4.2.26 on 2025-12-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('size_range', models.CharField(blank=True, max_length=50)),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('seats_required', models.IntegerField()),
                ('space_type', models.CharField(choices=[('OPEN', 'Open Desk'), ('DEDICATED', 'Dedicated Desk'), ('CABIN', 'Private Cabin'), ('MEETING', 'Meeting Room Only')], max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('duration_months', models.IntegerField(blank=True, null=True)),
                ('budget_per_seat', models.IntegerField(blank=True, null=True)),
                ('amenities', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('IN_REVIEW', 'In Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ON_HOLD', 'On Hold')], default='NEW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
